packages:
  - packages/*
  - apps/cosmic-horizons-api
  - apps/cosmic-horizons-api-e2e
  - apps/cosmic-horizons-web
  - apps/cosmic-horizons-web-e2e
  - libs/shared/*

autoInstallPeers: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - esbuild
  - less
  - lmdb
  - msgpackr-extract
  - nx
  - pulsar-client
  - unrs-resolver

overrides:
  '@mapbox/node-pre-gyp': ^2.0.2
  ajv@<6.14.0: '>=6.14.0'
  ajv@>=7.0.0-alpha.0 <8.18.0: '>=8.18.0'
  hono@<4.11.10: '>=4.11.10'
  minimatch@<10.2.1: '>=10.2.1'
  tar: ^7.5.7
  tar@<7.5.8: '>=7.5.8'
